version: '3.8'

services:
  # Nginx
  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./example-app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel-network

  # PHP-FPM
  php:
    build:
      context: ./docker/php
    container_name: laravel-php
    volumes:
      - ./example-app:/var/www/html
    networks:
      - laravel-network

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: laravel-postgres
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - laravel-network

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: laravel-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - laravel-network

volumes:
  postgres-data:

networks:
  laravel-network:
    driver: bridge
